# Generated by Django 5.2.8 on 2025-11-24 10:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='diagnostic_propose',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='session',
            name='historique_cache',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='session',
            name='questions_posees',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='HistoriqueSession',
            fields=[
                ('id_historique', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sessions_completees', models.JSONField(default=list)),
                ('derniere_activite', models.DateTimeField(default=django.utils.timezone.now)),
                ('historique_complet', models.JSONField(default=list)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.utilisateur')),
            ],
        ),
    ]
