# Generated by Django 5.2.8 on 2025-11-19 12:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expert', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LearnerProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery_score', models.FloatField(default=0.0, help_text='Score de 0.0 (non vu) à 1.0 (maîtrisé).')),
                ('last_interaction_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('interaction_history', models.JSONField(default=list, help_text='Liste des interactions (questions/réponses).')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert.concept')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learner.learnerprofile')),
            ],
            options={
                'unique_together': {('learner', 'concept')},
            },
        ),
    ]
