# Generated by Django 5.2.8 on 2025-11-25 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerprofile',
            name='domaine',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='niveau_app',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='niveau_expertise',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='performance_par_domaine',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='specialite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='learnerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learnerprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
