# Generated by Django 5.2.8 on 2025-11-25 18:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialite', models.CharField(default='Médecine Générale', max_length=100)),
                ('niveau_expertise', models.CharField(default='DEBUTANT', max_length=50)),
                ('niveau_app', models.CharField(default='1', max_length=50)),
                ('domaine', models.CharField(default='Santé', max_length=100)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
